Presentation.Web/Models/AdminSettings/SettingsAdminViewModel.cs
using Core.DomainModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Web.Models.SettingsAdmin
{
    public class SettingsAdminViewModel
    {
        [DisplayName("Forening forside tekst")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string FrontpageTextForening { get; set; }

        [DisplayName("Ildsjæl forside tekst")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string FrontpageTextIldsjael { get; set; }

        [DisplayName("Forening forside overskrift")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string FrontpageTitleForening { get; set; }

        [DisplayName("Ildsjæl forside overskrift")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string FrontpageTitleIldsjael { get; set; }

        [DisplayName("Om Os Forening tekst")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string ForeningAboutText { get; set; }

        [DisplayName("Om Os Ildsjæl tekst")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string IldsjaelAboutText { get; set; }

        [DisplayName("Startside konkurrence")]
        public ContestType DefaultContestType { get; set; }

        [DisplayName("Upload nyt Ildsjæl Forside billede")]
        public virtual HttpPostedFileBase IldsjaelFrontpagePicture { get; set; }

        [DisplayName("Upload nyt Ildsjæl Om konkurrencen billede")]
        public virtual HttpPostedFileBase IldsjaelAboutPicture { get; set; }

        [DisplayName("Upload nyt Forening Forside billede")]
        public virtual HttpPostedFileBase ForeningFrontpagePicture { get; set; }

        [DisplayName("Upload nyt Forening Om konkurrencen billede")]
        public virtual HttpPostedFileBase ForeningAboutPicture { get; set; }

        [DisplayName("Skjul \"Årets Forening/Andre Lokale Formål\" på Ildsjæl forsiden?")]
        public bool ForeningHidden { get; set; }

        [DisplayName("Skjul \"Årets Ildsjæl\" på Forening/Formål forsiden?")]
        public bool IldsjaelHidden { get; set; }

        public string Message { get; set; }
    }
}

Presentation.Web/Controllers/AdminSettingsController.cs
using System.IO;
using System.Web;
using System.Web.Mvc;
using Core.ApplicationServices;
using Ganss.XSS;
using Presentation.Web.Models.SettingsAdmin;

namespace Presentation.Web.Controllers
{
    [Authorize]
    public class AdminSettingsController : Controller
    {
        private readonly ISettingHelper _settingsHelper;
        private readonly string _ildsjaelFrontpageBannerPath;
        private readonly string _ildsjaelAboutBannerPath;
        private readonly string _foreningFrontpageBannerPath;
        private readonly string _foreningAboutBannerPath;

        public AdminSettingsController(
            ISettingHelper settingsHelper,
            string ildsjaelFrontpageBannerPath,
            string ildsjaelAboutBannerPath,
            string foreningFrontpageBannerPath,
            string foreningAboutBannerPath)
        {
            _settingsHelper = settingsHelper;
            _ildsjaelFrontpageBannerPath = ildsjaelFrontpageBannerPath;
            _ildsjaelAboutBannerPath = ildsjaelAboutBannerPath;
            _foreningFrontpageBannerPath = foreningFrontpageBannerPath;
            _foreningAboutBannerPath = foreningAboutBannerPath;
        }

        [Route("~/admin/settings")]
        public ActionResult Index()
        {
            var vm = new SettingsAdminViewModel()
            {
                FrontpageTextForening = _settingsHelper.GetFrontpageTextForening(),
                FrontpageTextIldsjael = _settingsHelper.GetFrontpageTextIldsjael(),
                FrontpageTitleForening = _settingsHelper.GetFrontpageTitleForening(),
                FrontpageTitleIldsjael = _settingsHelper.GetFrontpageTitleIldsjael(),
                ForeningAboutText = _settingsHelper.GetForeningAboutText(),
                IldsjaelAboutText = _settingsHelper.GetIldsjaelAboutText(),
                DefaultContestType = _settingsHelper.GetDefaultContestType(),
                ForeningHidden = _settingsHelper.GetForeningHidden(),
                IldsjaelHidden = _settingsHelper.GetIldsjaelHidden()
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("~/admin/settings")]
        public ActionResult Index(SettingsAdminViewModel vm)
        {
            var sanitizer = new HtmlSanitizer();

            _settingsHelper.SetFrontpageTextForening(sanitizer.Sanitize(vm.FrontpageTextForening));
            _settingsHelper.SetFrontpageTextIldsjael(sanitizer.Sanitize(vm.FrontpageTextIldsjael));
            _settingsHelper.SetFrontpageTitleForening(sanitizer.Sanitize(vm.FrontpageTitleForening));
            _settingsHelper.SetFrontpageTitleIldsjael(sanitizer.Sanitize(vm.FrontpageTitleIldsjael));
            _settingsHelper.SetForeningAboutText(sanitizer.Sanitize(vm.ForeningAboutText));
            _settingsHelper.SetIldsjaelAboutText(sanitizer.Sanitize(vm.IldsjaelAboutText));
            _settingsHelper.SetDefaultContestType(vm.DefaultContestType);
            _settingsHelper.SetForeningHidden(vm.ForeningHidden);
            _settingsHelper.SetIldsjaelHidden(vm.IldsjaelHidden);

            if (vm.IldsjaelFrontpagePicture != null)
                HandleFileUpload(vm.IldsjaelFrontpagePicture, _ildsjaelFrontpageBannerPath);

            if (vm.IldsjaelAboutPicture != null)
                HandleFileUpload(vm.IldsjaelAboutPicture, _ildsjaelAboutBannerPath);

            if (vm.ForeningFrontpagePicture != null)
                HandleFileUpload(vm.ForeningFrontpagePicture, _foreningFrontpageBannerPath);

            if (vm.ForeningAboutPicture != null)
                HandleFileUpload(vm.ForeningAboutPicture, _foreningAboutBannerPath);

            vm.Message = "Indstillinger blev gemt";

            return View(vm);
        }

        private void HandleFileUpload(HttpPostedFileBase file, string filePath)
        {
            if (file.ContentLength > 0)
            {
                using (var writer = new FileStream(filePath, FileMode.OpenOrCreate))
                {
                    file.InputStream.Position = 0;
                    file.InputStream.CopyTo(writer);
                }
            }
        }
    }
}

Presentation.Web/Views/AdminSettings/Index.cshtml
@model Presentation.Web.Models.SettingsAdmin.SettingsAdminViewModel

@{
    ViewBag.Title = "Indstillinger - Admin";
}

<div style="padding: 10px;">

    <h2>Indstillinger</h2>

    @if (!String.IsNullOrWhiteSpace(Model.Message))
    {
        <div class="alert alert-success" role="alert">@Model.Message</div>
    }


    @using (Html.BeginForm("Index", "AdminSettings", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />

            <div class="form-group">
                @Html.LabelFor(model => model.DefaultContestType, htmlAttributes: new { @class = "control-label col-xs-2" })
                <div class="col-md-9">
                    @Html.EnumDropDownListFor(model => model.DefaultContestType, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DefaultContestType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">
                    <h2><b>Skift Forening tekst</b></h2>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FrontpageTitleForening, htmlAttributes: new { @class = "control-label col-xs-2" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.FrontpageTitleForening, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FrontpageTitleForening, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">
                    <p>
                        Til overskrift vælges <b><em>H1</em></b> under <b><em>Paragraph</em></b> (til højre for <em>formats</em>)
                        Teksten vil på forsiden som udgangspunkt være hvid. Vælg kun anden farve for at overskrive denne.
                    </p>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.FrontpageTextForening, htmlAttributes: new { @class = "control-label col-xs-2" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.FrontpageTextForening, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FrontpageTextForening, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">
                    <p>
                        Til overskrift vælges <b><em>H2</em></b> under <b><em>Paragraph</em></b> (til højre for <em>formats</em>).
                        Til brødtekst vælges <b><em>Paragraph.</em></b>
                        Teksten vil på forsiden som udgangspunkt være hvid. Vælg kun anden farve for at overskrive denne.
                    </p>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ForeningAboutText, htmlAttributes: new { @class = "control-label col-xs-2" })
                <div class="col-md-9">
                    @Html.TextAreaFor(model => model.ForeningAboutText, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ForeningAboutText, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">
                    <p>
                        Til overskrift vælges <b><em>H1</em></b> under <b><em>Paragraph</em></b> (til højre for <em>formats</em>).
                        Til brødtekst vælges <b><em>Paragraph.</em></b>
                        Til pligttekst vælges <b><em>H5</em></b>
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">
                    <h2><b>Upload billeder</b></h2>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ForeningFrontpagePicture, htmlAttributes: new { @class = "control-label col-xs-2" })
                <div class="col-md-9">
                    <input type="file" name="@Html.NameFor(x => x.ForeningFrontpagePicture)" />
                    @Html.ValidationMessageFor(model => model.ForeningFrontpagePicture, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ForeningAboutPicture, htmlAttributes: new {@class = "control-label col-xs-2"})
                <div class="col-md-9">
                    <input type="file" name="@Html.NameFor(x => x.ForeningAboutPicture)"/>
                    @Html.ValidationMessageFor(model => model.ForeningAboutPicture, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="row">
                <div class="col-xs-10 col-xs-offset-2">&nbsp;</div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-9">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>

@section scripts {
    <script src='https://cdn.tinymce.com/4/tinymce.min.js'></script>
    <script src="/Scripts/site/admin.js"></script>
}