Presentation.Web/Models/Menu/ForeningMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Presentation.Web.Models.Menu
{
    public class ForeningMenuViewModel
    {
        public bool IldsjaelHidden { get; set; }
    }
}

Presentation.Web/Models/Menu/IldsjaelMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Presentation.Web.Models.Menu
{
    public class IldsjaelMenuViewModel
    {
        public bool ForeningHidden { get; set; }
    }
}

Presentation.Web/Controllers/AboutController.cs
using System.Web.Mvc;
using Presentation.Web.Models.About;
using Core.ApplicationServices;

namespace Presentation.Web.Controllers
{
    public class AboutController : Controller
    {
        private readonly ISettingHelper _settingsHelper;
        private readonly string _ildsjaelBannerUrl;
        private readonly string _foreningBannerUrl;

        public AboutController(
            ISettingHelper settingsHelper,
            string ildsjaelBannerUrl,
            string foreningBannerUrl)
        {
            _settingsHelper = settingsHelper;
            _ildsjaelBannerUrl = ildsjaelBannerUrl;
            _foreningBannerUrl = foreningBannerUrl;
        }

        [Route("~/forening/om")]
        public ActionResult ForeningAbout()
        {
            var vm = new ForeningAboutViewModel()
            {
                photoUrl = _foreningBannerUrl,
                AboutText = _settingsHelper.GetForeningAboutText()
            };

            return View(vm);
        }
    }
}

Presentation.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.ApplicationServices;
using Presentation.Web.Models.Menu;

namespace Presentation.Web.Controllers
{
    [ChildActionOnly]
    public class MenuController : Controller
    {
        private readonly ISettingHelper _settingsHelper;

        public MenuController(ISettingHelper settingsHelper)
        {
            _settingsHelper = settingsHelper;
        }

        public ActionResult Forening()
        {
            var vm = new ForeningMenuViewModel();

            return View(vm);
        }
    }
}

Presentation.Web/Controllers/NominateForeningController.cs
using AutoMapper;
using Core.ApplicationServices;
using Core.ApplicationServices.Images;
using Core.ApplicationServices.NomineeFiles;
using Core.DomainModel;
using Core.DomainServices;
using Postal;
using Presentation.Web.Emails;
using Presentation.Web.Models.Nominate;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Presentation.Web.Controllers
{
    public class NominateForeningController : NominateControllerBase<ForeningNominee, NominateForeningViewModel, AcceptForeningViewModel>
    {
        private readonly IEmailService _emailService;
        private readonly Uri _baseUrl;

        public NominateForeningController(
            IMapper mapper,
            IUnitOfWork unitOfWork,
            IGenericRepository<Nominee> nomineeRepo,
            IGenericRepository<Picture> pictureRepo,
            IGenericRepository<Category> categoryRepo,
            INomineeFiles nomineeFiles,
            IContestHelper contestHelper,
            IFileLocator fileLocator,
            IImageValidator imgValidator,
            IImageRotate imgRotate,
            IEmailService emailService,
            string defaultPicture,
            int maxUploadSize,
            Uri baseUrl,
            IRealtorService realtorService,
            bool useRealtorMailService)
            : base(ContestType.Forening,
                   mapper,
                   unitOfWork,
                   nomineeRepo,
                   pictureRepo,
                   categoryRepo,
                   nomineeFiles,
                   contestHelper,
                   fileLocator,
                   imgValidator,
                   imgRotate,
                   defaultPicture,
                   maxUploadSize,
                   realtorService,
                   useRealtorMailService)
        {
            _emailService = emailService;
            _baseUrl = baseUrl;
        }

        [HttpGet]
        [Route("~/forening/nominer")]
        public override ActionResult Nominate()
        {
            return base.Nominate();
        }

        [HttpPost]
        [Route("~/forening/nominer")]
        public override ActionResult Nominate(NominateForeningViewModel vm)
        {
            return base.Nominate(vm);
        }

        [HttpGet]
        [Route("~/forening/tak")]
        public override ActionResult Thanks(string NomineeName)
        {
            return base.Thanks(NomineeName);
        }

        [HttpGet]
        [Route("~/forening/accepter")]
        public override ActionResult Accept(Guid guid)
        {
            return base.Accept(guid);
        }

        [HttpPost]
        [Route("~/forening/accepter")]
        public override ActionResult Accept(AcceptForeningViewModel vm)
        {
            return base.Accept(vm);
        }

        [HttpGet]
        [Route("~/forening/afvis")]
        public override ActionResult Decline(Guid guid)
        {
            return base.Decline(guid);
        }

        protected override void SendNominatorThanksEmail(Nominee nominee)
        {
            var email = new ForeningNominatorThanksEmail()
            {
                Nominee = (ForeningNominee)nominee,
            };
            _emailService.Send(email);
        }

        protected override void SendNominationEmail(Nominee nominee)
        {
            var acceptUrl = new Uri(_baseUrl, Url.Action(nameof(Accept), new { guid = nominee.Guid }));
            var aboutUrl = new Uri(_baseUrl, Url.Action(nameof(AboutController.ForeningAbout), nameof(AboutController).Replace("Controller", "")));
            var email = new ForeningNominationEmail()
            {
                Nominee = (ForeningNominee)nominee,
                AcceptUrl = acceptUrl,
                AboutUrl = aboutUrl
            };
            _emailService.Send(email);
        }

        protected override void SendNomineeAcceptedEmail(Nominee nominee)
        {
            var url = new Uri(_baseUrl, Url.Action(nameof(Accept), new {guid = nominee.Guid}));
            var DetailsUrl = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new { slug = nominee.Slug, id = nominee.Id }));
            var email = new ForeningNomineeAcceptedEmail()
            {
                Nominee = (ForeningNominee)nominee,
                EditUrl = url,
                NomineeUrl = DetailsUrl
            };
            _emailService.Send(email);
        }

        protected override void SendNominatorAcceptedEmail(Nominee nominee)
        {
            var url = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new {slug = nominee.Slug, id = nominee.Id}));
            var email = new ForeningNominatorAcceptedEmail()
            {
                Nominee = (ForeningNominee)nominee,
                NomineeUrl = url,
            };
            _emailService.Send(email);
        }

        protected override void SendRealtorAcceptedEmail(Nominee nominee, IList<Realtor> realtorList)
        {
            var url = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new { slug = nominee.Slug, id = nominee.Id }));

            foreach (var realtor in realtorList)
            {
                var email = new RealtorAcceptedEmail()
                {
                    Nominee = (ForeningNominee)nominee,
                    NomineeUrl = url,
                    Realtor = realtor
                };
                _emailService.Send(email);
            }
        }

        protected override string GetDetailsUrl(Nominee nominee)
        {
            object param = new { slug = nominee.Slug, id = nominee.Id };
            var uri = new Uri(_baseUrl, Url.Action("Details", "NomineeForening", param));
            return uri.ToString();
        }
    }
}

Presentation.Web/Controllers/NomineeForeningController.cs
using System;
using AutoMapper;
using Core.ApplicationServices;
using Core.DomainModel;
using Core.DomainServices;
using Presentation.Web.Models.Nominee;
using System.Web.Mvc;
using Core.ApplicationServices.Facebook;
using Presentation.Web.Emails;

namespace Presentation.Web.Controllers
{
    public class NomineeForeningController : NomineeControllerBase<ForeningNominee, ForeningDetailsViewModel, ForeningIndexViewModel>
    {
        public NomineeForeningController(
            IMapper mapper,
            IGenericRepository<Nominee> nomineeRepo,
            IContestHelper contestHelper,
            IVoteHelper voteHelper,
            IFacebookAuthHelper fbAuth,
            IFileLocator fileLocator,
            ISettingHelper settingHelper,
            string defaultPicture,
            Uri baseUrl,
            string bannerUrl,
            string twitterShareMessage)
            : base(ContestType.Forening,
                   mapper,
                   nomineeRepo,
                   contestHelper,
                   voteHelper,
                   fbAuth,
                   fileLocator,
                   settingHelper,
                   defaultPicture,
                   baseUrl,
                   bannerUrl,
                   twitterShareMessage) {}

        [HttpGet]
        [Route("~/forening")]
        public override ActionResult Index()
        {
            return base.Index();
        }

        [HttpGet]
        [Route("~/forening/{slug}-{id:int}")]
        public override ActionResult Details(string slug, int id)
        {
            return base.Details(slug, id);
        }

        protected override void SendRecommendEmail(Nominee nominee, RecommendViewModel vm)
        {
            var email = new ForeningRecommendEmail()
            {
                Nominee = (ForeningNominee)nominee,
                NomineeDetailsUrl = GetDetailsUrl(nominee),
                SenderName = vm.SenderName,
                SenderEmail = vm.SenderEmail,
                RecipientName = vm.RecipientName,
                RecipientEmail = vm.RecipientEmail,
                Message = vm.Message,
            };

            email.Send();
        }
    }
}

Presentation.Web/Views/Menu/Forening.cshtml
@model Presentation.Web.Models.Menu.ForeningMenuViewModel
<div class="navbar-header mobile-nav">
    <div class="col-md-10 col-md-offset-1 navbar-margin col-xs-12">
        <div class="row">
            <a class="header-home hidden-xs" href="http://www.home.dk" target="_blank">
                <img class="pull-right" src="@Url.Content("~/Content/Images/home/home-leave-icon.png")"/>
                <div class="home-text pull-right">
                    home.dk
                </div>
            </a>
            <a class="header-home hidden-xs" href="https://homeprisen2017.home.dk" target="_blank">
                <img class="pull-right" src="@Url.Content("~/Content/Images/home/home-leave-icon.png")"/>
                <div class="home-text pull-right">
                    homePrisen 2017
                </div>
            </a>
        </div>
        <div class="row">
            <div class="header-home-logo col-xs-1 hidden-xs">
                <a class="navbar-logo" href="@Url.Action("Index", "NomineeForening")">
                    <img src="@Url.Content("~/Content/Images/home/Home-logo.png")" />
                </a>
            </div>
            <div class="col-md-9 col-xs-12 pull-right" style="padding-right: 0;">
                <ul id="navbar-links" class="nav navbar-nav navbar-right">
                    <li class="text-nav-link"><a href="@Url.Action("Index", "NomineeForening")" class="text-navbar-link-color">Stem på favorit</a></li>
                    <li class="text-nav-link"><a href="@Url.Action("Nominate", "NominateForening")" class="text-navbar-link-color">Tilmeld konkurrencen</a></li>
                    <li class="text-nav-link"><a href="@Url.Action("ForeningAbout", "About")" class="text-navbar-link-color">Om homePrisen</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

Presentation.Web/Views/Menu/Ildsjael.cshtml
@model Presentation.Web.Models.Menu.IldsjaelMenuViewModel

<!--row 1-->
<div class="row">
    <!--Group logo + brand + toggle for better mobile view-->
    <div class="navbar-header bg-subRow">
        <div class="visible-xs">
            <a href="@Url.Action("Index", "NomineeIldsjael")" class="navbar-logo pull-left">
                <img src='@Url.Content("/Content/Images/logo@2x.png")' />
            </a>


            <a href='@Url.Action("Index", "NomineeIldsjael")' class="navbar-brand navbar-brand-custom pull-left">
                <h5 class="h5-navbar "><b>HOLDER DE LOKALE KØRENDE</b></h5>
            </a>
        </div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!--nav bar row 1-->
    <div class="navbar-collapse collapse collapse-navbar-mobile">
        <ul class="nav navbar-nav navbar-right">

            @*navbar links with ropdown for mobile view*@

            <!--empty menuitems used to space dropdown in mobile view-->
            <li class="dropdown text-center open visible-xs">
                <a href="" id="dropdownIldsjael" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                    Årets Ildsjæl
                </a>
                <ul class="dropdown-menu" id="dropdown-menu-1">
                    <li class="text-nav-dropdown ">@Html.ActionLink("Stem på din favorit", "Index", "NomineeIldsjael")</li>
                    <li class="text-nav-dropdown ">@Html.ActionLink("Nominér en ildsjæl", "Nominate", "NominateIldsjael")</li>
                    <li class="text-nav-dropdown ">@Html.ActionLink("Om konkurrencen", "IldsjaelAbout", "About")</li>
                </ul>
            </li>
            @if (!Model.ForeningHidden)
            {
                <li class="dropdown text-center visible-xs">
                    <a href="" id="dropdownClub" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Årets Forening og andre lokale Formål
                    </a>
                    <ul class="dropdown-menu" id="dropdown-menu-2">
                        <li class="text-nav-dropdown ">@Html.ActionLink("Stem på din favorit", "Index", "NomineeForening")</li>
                        <li class="text-nav-dropdown ">@Html.ActionLink("Nominér Forening", "Nominate", "NominateForening")</li>
                        <li class="text-nav-dropdown ">@Html.ActionLink("Om konkurrencen", "ForeningAbout", "About")</li>
                    </ul>
                </li>
            }
            <li><a href="http://www.goon.nu" target="_blank" class=" visible-xs">Goon.nu</a></li>
            <li class="visible-xs">
                <a href="@Url.Action("Index","NomineeIldsjael")" class="navbar-dropdown-logo ">
                    <img class="center-block " src='@Url.Content("/Content/Images/logo@2x.png")' />
                </a>
            </li>

            @*Navbar links for desktop view*@

            <li class="text-center hidden-xs">
                <a href="@Url.Action("Index", "NomineeIldsjael")" class=" text-goon-green-light">Årets Ildsjæl</a>
                <div class="icon-container hidden-xs text-center">
                    <span class=" glyphicon glyphicon-triangle-top ildsjael"></span>
                </div>
            </li>
            @if (!Model.ForeningHidden)
            {
                <li class="text-center hidden-xs">
                    <a href="@Url.Action("Index","NomineeForening")">Årets Forening og andre lokale Formål</a>
                </li>
            }
            <li><a href="http://www.goon.nu" target="_blank" class=" hidden-xs">Goon.nu</a></li>
        </ul>
    </div>
</div>
<!--row 2-->
<div class="row bg-subRow subRow hidden-xs">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-md-offset-1">
                <a href="@Url.Action("Index", "NomineeIldsjael")" class="pull-left">
                    <img src='@Url.Content("/Content/Images/logo@2x.png")' />
                </a>

                <a href='@Url.Action("Index", "NomineeIldsjael")' class="navbar-brand navbar-brand-custom pull-left">
                    <h5 class="h5-navbar "><b>HOLDER DE LOKALE KØRENDE</b></h5>
                </a>
            </div>
        </div>
    </div>
    <ul class="list-inline list-unstyled pull-right navbar-sub-link-ul hidden-xs">
        <li class="text-nav-sub-link "><a href="@Url.Action("Index", "NomineeIldsjael")" class="text-navbar-sub-link-link-color">Stem på din favorit</a></li>
        <li class="text-nav-sub-link "><a href="@Url.Action("Nominate", "NominateIldsjael")" class="text-navbar-sub-link-link-color">Nominér en ildsjæl</a></li>
        <li class="text-nav-sub-link "><a href="@Url.Action("IldsjaelAbout", "About")" class="text-navbar-sub-link-link-color">Om konkurrencen</a></li>
    </ul>
</div>