Presentation.Web/Models/AdminNominee/ForeningNomineeAdminViewModel.cs
using Core.DomainModel;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Presentation.Web.Models.NomineeAdmin
{
    public class ForeningNomineeAdminViewModel : NomineeAdminViewModel
    {
        public Guid Guid { get; set; }
        public int Id { get; set; }

        [DisplayName("Navn")]
        public string Name { get; set; }

        [DisplayName("Navn på formand / ansvarlig")]
        public string ResponsibleName { get; set; }

        [DisplayName("Formandens e-mail")]
        public string Email { get; set; }

        [DisplayName("Formandens telefonnummer")]
        public string Phone { get; set; }

        [DisplayName("Formandens adresse")]
        public string Address { get; set; }

        [DisplayName("Postnummer")]
        public string Zipcode { get; set; }

        [DisplayName("By")]
        public string City { get; set; }

        [DisplayName("Begrundelse")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Accepteret")]
        public bool IsAccepted { get; set; }

        [DisplayName("Stemmer")]
        public int VoteCount { get; set; }

        [DisplayName("Placering")]
        public int Rank { get; set; }

        [DisplayName("Nominator navn")]
        public string NominatorName { get; set; }

        [DisplayName("Nominator e-mail")]
        public string NominatorEmail { get; set; }

        [DisplayName("Nominator telefon")]
        public string NominatorPhone { get; set; }

        [DisplayName("Nomineret tid")]
        public DateTime Nominated { get; set; }

        [DisplayName("Accepteret tid")]
        public DateTime Accepted { get; set; }

        // The contest to be nominated in
        [DisplayName("Konkurrence")]
        public virtual Contest Contest { get; set; }
        public int ContestId { get; set; }

        [DisplayName("Forening/formål")]
        public ForeningType ForeningType { get; set; }

        [DisplayName("Antal medlemmer")]
        public int MemberCount { get; set; }

        public string Category { get; set; }
        public string Municipality { get; set; }
    }
}

Presentation.Web/Models/AdminNominee/IldsjaelNomineeAdminViewModel.cs
using Core.DomainModel;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Presentation.Web.Models.NomineeAdmin
{
    public class IldsjaelNomineeAdminViewModel : NomineeAdminViewModel
    {
        public Guid Guid { get; set; }
        public int Id { get; set; }

        [DisplayName("Navn")]
        public string Name { get; set; }

        [DisplayName("Titel")]
        public string Title { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Telefon")]
        public string Phone { get; set; }

        [DisplayName("Adresse")]
        public string Address { get; set; }

        [DisplayName("Postnummer")]
        public string Zipcode { get; set; }

        [DisplayName("By")]
        public string City { get; set; }

        [DisplayName("Begrundelse")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Accepteret")]
        public bool IsAccepted { get; set; }

        [DisplayName("Stemmer")]
        public int VoteCount { get; set; }

        [DisplayName("Placering")]
        public int Rank { get; set; }

        [DisplayName("Nominator navn")]
        public string NominatorName { get; set; }

        [DisplayName("Nominator e-mail")]
        public string NominatorEmail { get; set; }

        [DisplayName("Nominator telefon")]
        public string NominatorPhone { get; set; }

        [DisplayName("Nomineret tid")]
        public DateTime Nominated { get; set; }

        [DisplayName("Accepteret tid")]
        public DateTime Accepted { get; set; }

        // The contest to be nominated in
        [DisplayName("Konkurrence")]
        public virtual Contest Contest { get; set; }
        public int ContestId { get; set; }

        // Picture to render posters etc. from
        public virtual Picture PictureUrl { get; set; }
    }
}

Presentation.Web/Models/AdminNominee/NomineeAdminViewModel.cs
using Core.DomainModel;
using System;
using System.ComponentModel;

namespace Presentation.Web.Models.NomineeAdmin
{
    public class NomineeAdminViewModel
    {
        public virtual Guid Guid { get; set; }
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual string Email { get; set; }
        public virtual string Phone { get; set; }
        public virtual string Address { get; set; }
        public virtual string Zipcode { get; set; }
        public virtual string City { get; set; }
        public virtual string Description { get; set; }
        public virtual bool IsAccepted { get; set; }
        public virtual int VoteCount { get; set; }
        public virtual int Rank { get; set; }
        public virtual string NominatorName { get; set; }
        public virtual string NominatorEmail { get; set; }
        public string NominatorPhone { get; set; }
        public virtual DateTime Nominated { get; set; }
        public virtual DateTime Accepted { get; set; }
        public virtual Contest Contest { get; set; }
        public virtual int ContestId { get; set; }

        [DisplayName("Link til at acceptere/rette")]
        public string AcceptDirectLink { get; set; }
        public string Category { get; set; }
        public string Municipality { get; set; }
    }
}

Presentation.Web/Models/AdminNominee/NomineeVotesViewModel.cs
using Core.DomainModel;
using System;
using System.ComponentModel;

namespace Presentation.Web.Models.NomineeAdmin
{
    public class NomineeVotesViewModel
    {
        public DateTime Created { get; set; }
        public string FacebookUserId { get; set; }
    }
}

Presentation.Web/Controllers/AdminNomineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using Core.DomainModel;
using Core.DomainServices;
using AutoMapper;
using Presentation.Web.Models.NomineeAdmin;
using Core.ApplicationServices.NomineeFiles;

namespace Presentation.Web.Controllers
{
    [Authorize]
    public class AdminNomineeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IGenericRepository<Nominee> _nomineeRepo;
        private readonly IGenericRepository<Contest> _contestRepo;
        private readonly IGenericRepository<Vote> _voteRepo;
        private readonly INomineeFiles _nomineeFiles;
        private readonly Uri _baseUrl;

        public AdminNomineeController(
            IMapper mapper,
            IUnitOfWork unitOfWork,
            IGenericRepository<Nominee> nomineeRepo,
            IGenericRepository<Contest> contestRepo,
            IGenericRepository<Vote> voteRepo,
            INomineeFiles nomineeFiles,
            Uri baseUrl)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
            _nomineeRepo = nomineeRepo;
            _contestRepo = contestRepo;
            _voteRepo = voteRepo;
            _nomineeFiles = nomineeFiles;
            _baseUrl = baseUrl;
        }

        [Route("~/admin/nominerede")]
        public ActionResult Index(string query = "", string sort = "", int? contestId = null, int page = 1)
        {
            int pageSize = 100;
            var nominees = _nomineeRepo.AsQueryable();

            // Filter by free text search query
            if(!string.IsNullOrWhiteSpace(query))
            {
                query = query.ToLower();
                nominees = nominees.Where(x => x.Name.ToLower().Contains(query) ||
                                               x.Email.ToLower().Contains(query) ||
                                               x.Phone.ToLower().Contains(query) ||
                                               x.City.ToLower().Contains(query));
            }

            // Order results
            switch(sort)
            {
                case "name":
                    nominees = nominees.OrderBy(x => x.Name);
                    break;
                case "votes":
                    nominees = nominees.OrderByDescending(x => x.VoteCount);
                    break;
                default:
                    nominees = nominees.OrderByDescending(x => x.Nominated);
                    break;
            }

            // Filter by contest
            if (contestId != null)
                nominees = nominees.Where(x => x.ContestId == contestId);

            var pagedList = nominees.ToPagedList(page, pageSize);
            var mapped = _mapper.Map<IEnumerable<NomineeAdminViewModel>>(nominees);

            ViewBag.Query = query;
            ViewBag.Sort = sort;
            ViewBag.ContestId = contestId;

            // Build SelectList for contests
            var contests = _contestRepo.AsQueryable().ToList();
            ViewBag.ContestSelect = new SelectList(contests, "Id", "Name", contestId);

            // Build SelectList for sorting options
            var sortSelect = new List<SelectListItem>()
            {
                new SelectListItem() { Value = "name", Text = "Navn" },
                new SelectListItem() { Value = "votes", Text = "Antal stemmer" },
                new SelectListItem() { Value = "nominated", Text = "Nyeste" },
            };
            ViewBag.SortSelect = new SelectList(sortSelect, "Value", "Text", sort);

            return View(mapped.ToPagedList(page, pageSize));
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var contests = _contestRepo.AsQueryable().ToList();
            var nominee = _nomineeRepo.AsQueryable().FirstOrDefault(x => x.Guid == id);
            Uri acceptDirectLink;

            if (nominee == null)
            {
                return HttpNotFound();
            }

            ViewBag.ContestId = new SelectList(contests, "Id", "Name", nominee.ContestId);
            var vm = _mapper.Map<ForeningNomineeAdminViewModel>(nominee);
            var path = Url.Action(nameof(NominateForeningController.Accept), "NominateForening",
                new { Guid = nominee.Guid });
            vm.AcceptDirectLink = new Uri(_baseUrl, path).ToString();
            return View("EditForening", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditForening(ForeningNomineeAdminViewModel vm)
        {
            var nominee = _mapper.Map<ForeningNominee>(vm);

            if (ModelState.IsValid)
            {
                _nomineeRepo.Update(nominee);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            var contests = _contestRepo.AsQueryable().ToList();
            ViewBag.ContestId = new SelectList(contests, "Id", "Name", nominee.ContestId);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditIldsjael(IldsjaelNomineeAdminViewModel vm)
        {
            var nominee = _mapper.Map<IldsjaelNominee>(vm);

            if (ModelState.IsValid)
            {
                _nomineeRepo.Update(nominee);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            var contests = _contestRepo.AsQueryable().ToList();
            ViewBag.ContestId = new SelectList(contests, "Id", "Name", nominee.ContestId);

            return View(vm);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var nominee = _nomineeRepo.AsQueryable().FirstOrDefault(x => x.Guid == id);
            if (nominee == null)
                return HttpNotFound();

            var vm = _mapper.Map<NomineeAdminViewModel>(nominee);
            return View(vm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var nominee = _nomineeRepo.AsQueryable().FirstOrDefault(x => x.Guid == id);
            if (nominee != null)
                _nomineeFiles.RemoveFiles(nominee);

            _nomineeRepo.DeleteByKey(id);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        public ActionResult ShowVotes(Guid id)
        {
            var votes = _voteRepo.AsQueryable().Where(x => x.NomineeGuid == id).OrderBy(x => x.Created);
            var mapped = Mapper.Map<IEnumerable<NomineeVotesViewModel>>(votes);

            return View(mapped);
        }
    }
}

Presentation.Web/Views/AdminNominee/EditForening.cshtml
@model Presentation.Web.Models.NomineeAdmin.ForeningNomineeAdminViewModel

@{
    ViewBag.Title = "Admin - Nominerede";
}

<h2>Ret forening</h2>
<p>
        @Html.ActionLink("Til oversigten", "Index")
        |
        @Html.ActionLink("Vis stemmer", "ShowVotes", new { id = Model.Guid })
</p>

@using (Html.BeginForm("EditForening", "AdminNominee"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Guid)
        @Html.HiddenFor(model => model.Category)
        @Html.HiddenFor(model => model.Municipality)

        <div class="form-group">
            @Html.LabelFor(model => model.AcceptDirectLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                <a target="_blank" href="@Model.AcceptDirectLink">@Model.AcceptDirectLink</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoteCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.VoteCount
                @Html.HiddenFor(model => model.VoteCount)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Rank
                @Html.HiddenFor(model => model.Rank)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nominated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Nominated
                @Html.HiddenFor(model => model.Nominated)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Accepted
                @Html.HiddenFor(model => model.Accepted)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAccepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAccepted)
                    @Html.ValidationMessageFor(model => model.IsAccepted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contest, "ContestId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownList("ContestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.MemberCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResponsibleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.ResponsibleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResponsibleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Presentation.Web/Views/AdminNominee/EditIldsjael.cshtml
@model Presentation.Web.Models.NomineeAdmin.IldsjaelNomineeAdminViewModel

@{
    ViewBag.Title = "Admin - Nominerede";
}

<h2>Ret ildsjæl</h2>
<p>
    @Html.ActionLink("Til oversigten", "Index")
    |
    @Html.ActionLink("Vis stemmer", "ShowVotes", new { id = Model.Guid })
</p>

@using (Html.BeginForm("EditIldsjael", "AdminNominee"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Guid)


        <div class="form-group">
            @Html.LabelFor(model => model.AcceptDirectLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                <a target="_blank" href="@Model.AcceptDirectLink">@Model.AcceptDirectLink</a>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoteCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.VoteCount
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Rank
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nominated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Nominated
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Accepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Model.Accepted
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAccepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAccepted)
                    @Html.ValidationMessageFor(model => model.IsAccepted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contest, "ContestId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.DropDownList("ContestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Zipcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zipcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NominatorPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.NominatorPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NominatorPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Presentation.Web/Views/AdminNominee/ShowVotes.cshtml
@model IEnumerable<Presentation.Web.Models.NomineeAdmin.NomineeVotesViewModel>

@{
    ViewBag.Title = "Admin - Nominerede";
}

<div style="padding: 10px">
    <h2>Vis stemmer</h2>

    <table cellpadding="4" cellspacing="2">
        <tr>
            <th>Tidspunkt</th>
            <th></th>
            <th>Facebook ID</th>
        </tr>

        @foreach (var vote in Model)
        {
            <tr>
                <td>@vote.Created</td>
                <td width="50"></td>
                <td><a href="https://www.facebook.com/@vote.FacebookUserId" target="_blank">@vote.FacebookUserId</a></td>
            </tr>
        }
    </table>
</div>