Presentation.Web/Models/Nominee/DetailsViewModel.cs
using System;
using Presentation.Web.Models.Shared;

namespace Presentation.Web.Models.Nominee
{
    // TODO: Comment
    public class DetailsViewModelBase
    {
        public bool IsActive { get; set; }
        public string BannerPhotoUrl { get; set; }
        public Guid Guid { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public int VoteCount { get; set; }
        public int Rank { get; set; }
        public int TotalNominees { get; set; }
        public string AbsoluteUrl { get; set; }
        public string RelativeUrl { get; set; }
        public string TwitterShareMessage { get; set; }

        public bool AllowVoting { get; set; }

        public string PictureUrl { get; set; }
        public string PictureAbsoluteUrl { get; set; }
        public PictureViewModel PosterSolid { get; set; }
        public PictureViewModel PosterFbPic { get; set; }
        public PictureViewModel FlyerSolid { get; set; }
        public PictureViewModel FlyerFbPic { get; set; }
        public PictureViewModel FbCover { get; set; }
        public PictureViewModel FbCoverSolid { get; set; }

        public DetailsViewModelBase()
        {
            PosterSolid = new PictureViewModel();
            PosterFbPic = new PictureViewModel();
            FlyerSolid = new PictureViewModel();
            FlyerFbPic = new PictureViewModel();
            FbCover = new PictureViewModel();
            FbCoverSolid = new PictureViewModel();
            IsActive = false;
        }
    }
}

Presentation.Web/Controllers/CommentController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Core.ApplicationServices;
using Core.ApplicationServices.Facebook;
using Core.DomainModel;
using Core.DomainServices;

namespace Presentation.Web.Controllers
{
    // TODO: Comment
    public class CommentController : Controller
    {
        private readonly IGenericRepository<Nominee> _nomineeRepo;
        private readonly IGenericRepository<Comment> _commentRepo;
        private readonly IContestHelper _contestHelper;
        private readonly ICommentHelper _commentHelper;
        private readonly IVoteHelper _voteHelper;
        private readonly IFacebookAuthHelper _fbAuth;

        public CommentController(
            IGenericRepository<Nominee> nomineeRepo,
            IGenericRepository<Comment> commentRepo,
            IContestHelper contestHelper,
            ICommentHelper commentHelper,
            IVoteHelper voteHelper,
            IFacebookAuthHelper fbAuth)
        {
            _nomineeRepo = nomineeRepo;
            _commentRepo = commentRepo;
            _contestHelper = contestHelper;
            _commentHelper = commentHelper;
            _voteHelper = voteHelper;
            _fbAuth = fbAuth;
        }

        /// <summary>
        /// Place a comment on a nominee. The voting person must be
        /// authenticated via Facebook and must have placed a vote on
        /// the nominee to be able to comment. Also, the contest, in which
        /// the nominee is nominated within, must be active.
        /// </summary>
        /// <param name="guid">Guid of nominee to comment on</param>
        /// <returns>Json encoded response (see implementation for details)</returns>
        [HttpPost]
        public ActionResult PlaceComment(Guid guid, string comment)
        {
            var query = _nomineeRepo.AsQueryable();
            var nominee = query.SingleOrDefault(n => n.Guid == guid && n.IsAccepted);

            // Invalid (unknown) Guid provided by client
            if (nominee == null)
                return Json(new { guid = guid, success = false, error = 1, message = "Nominee not found" });

            // Contest is inactive
            if (!_contestHelper.ContestIsActive(nominee.Contest))
                return Json(new { guid = nominee.Guid, success = false, error = 2, message = "Contest is currently not active" });

            // User is not authenticated via Facebook
            if (!_fbAuth.IsRegistered())
                return Json(new { guid = nominee.Guid, success = false, error = 3, message = "User is not authenticated via Facebook" });

            // User has not voted on this nominee
            if (!_voteHelper.HasVotedOn(_fbAuth.UserId, nominee))
                return Json(new { guid = nominee.Guid, success = false, error = 4, message = "User has not voted on this nominee" });

            // User has not voted on this nominee
            if (_commentHelper.HasCommentedOn(_fbAuth.UserId, nominee))
                return Json(new { guid = nominee.Guid, success = false, error = 5, message = "User has already commented on this nominee" });

            // Validation success!
            _commentHelper.PlaceComment(nominee, _fbAuth, comment);
            return Json(new { guid = nominee.Guid, success = true });
        }

        // TODO: Comment
        [HttpGet]
        public ActionResult GetComments(Guid nomineeId, int offset = 0, int limit = 10)
        {
            var query = _commentRepo.AsQueryable()
                .Where(c => c.NomineeId == nomineeId)
                .OrderByDescending(c => c.Submitted);
            var total = query.Count();

            // Make json
            var responseData = new
            {
                total = total,
                offset = offset,
                entries = query.Skip(offset).Take(limit).ToList(),
            };

            return Json(responseData, JsonRequestBehavior.AllowGet);
        }
    }
}

Presentation.Web/Controllers/NominateForeningController.cs
using AutoMapper;
using Core.ApplicationServices;
using Core.ApplicationServices.Images;
using Core.ApplicationServices.NomineeFiles;
using Core.DomainModel;
using Core.DomainServices;
using Postal;
using Presentation.Web.Emails;
using Presentation.Web.Models.Nominate;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Presentation.Web.Controllers
{
    public class NominateForeningController : NominateControllerBase<ForeningNominee, NominateForeningViewModel, AcceptForeningViewModel>
    {
        private readonly IEmailService _emailService;
        private readonly Uri _baseUrl;

        public NominateForeningController(
            IMapper mapper,
            IUnitOfWork unitOfWork,
            IGenericRepository<Nominee> nomineeRepo,
            IGenericRepository<Picture> pictureRepo,
            IGenericRepository<Category> categoryRepo,
            INomineeFiles nomineeFiles,
            IContestHelper contestHelper,
            IFileLocator fileLocator,
            IImageValidator imgValidator,
            IImageRotate imgRotate,
            IEmailService emailService,
            string defaultPicture,
            int maxUploadSize,
            Uri baseUrl,
            IRealtorService realtorService,
            bool useRealtorMailService)
            : base(ContestType.Forening,
                   mapper,
                   unitOfWork,
                   nomineeRepo,
                   pictureRepo,
                   categoryRepo,
                   nomineeFiles,
                   contestHelper,
                   fileLocator,
                   imgValidator,
                   imgRotate,
                   defaultPicture,
                   maxUploadSize,
                   realtorService,
                   useRealtorMailService)
        {
            _emailService = emailService;
            _baseUrl = baseUrl;
        }

        [HttpGet]
        [Route("~/forening/nominer")]
        public override ActionResult Nominate()
        {
            return base.Nominate();
        }

        [HttpPost]
        [Route("~/forening/nominer")]
        public override ActionResult Nominate(NominateForeningViewModel vm)
        {
            return base.Nominate(vm);
        }

        [HttpGet]
        [Route("~/forening/tak")]
        public override ActionResult Thanks(string NomineeName)
        {
            return base.Thanks(NomineeName);
        }

        [HttpGet]
        [Route("~/forening/accepter")]
        public override ActionResult Accept(Guid guid)
        {
            return base.Accept(guid);
        }

        [HttpPost]
        [Route("~/forening/accepter")]
        public override ActionResult Accept(AcceptForeningViewModel vm)
        {
            return base.Accept(vm);
        }

        [HttpGet]
        [Route("~/forening/afvis")]
        public override ActionResult Decline(Guid guid)
        {
            return base.Decline(guid);
        }

        protected override void SendNominatorThanksEmail(Nominee nominee)
        {
            var email = new ForeningNominatorThanksEmail()
            {
                Nominee = (ForeningNominee)nominee,
            };
            _emailService.Send(email);
        }

        protected override void SendNominationEmail(Nominee nominee)
        {
            var acceptUrl = new Uri(_baseUrl, Url.Action(nameof(Accept), new { guid = nominee.Guid }));
            var aboutUrl = new Uri(_baseUrl, Url.Action(nameof(AboutController.ForeningAbout), nameof(AboutController).Replace("Controller", "")));
            var email = new ForeningNominationEmail()
            {
                Nominee = (ForeningNominee)nominee,
                AcceptUrl = acceptUrl,
                AboutUrl = aboutUrl
            };
            _emailService.Send(email);
        }

        protected override void SendNomineeAcceptedEmail(Nominee nominee)
        {
            var url = new Uri(_baseUrl, Url.Action(nameof(Accept), new {guid = nominee.Guid}));
            var DetailsUrl = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new { slug = nominee.Slug, id = nominee.Id }));
            var email = new ForeningNomineeAcceptedEmail()
            {
                Nominee = (ForeningNominee)nominee,
                EditUrl = url,
                NomineeUrl = DetailsUrl
            };
            _emailService.Send(email);
        }

        protected override void SendNominatorAcceptedEmail(Nominee nominee)
        {
            var url = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new {slug = nominee.Slug, id = nominee.Id}));
            var email = new ForeningNominatorAcceptedEmail()
            {
                Nominee = (ForeningNominee)nominee,
                NomineeUrl = url,
            };
            _emailService.Send(email);
        }

        protected override void SendRealtorAcceptedEmail(Nominee nominee, IList<Realtor> realtorList)
        {
            var url = new Uri(_baseUrl,
                Url.Action("Details", "NomineeForening", new { slug = nominee.Slug, id = nominee.Id }));

            foreach (var realtor in realtorList)
            {
                var email = new RealtorAcceptedEmail()
                {
                    Nominee = (ForeningNominee)nominee,
                    NomineeUrl = url,
                    Realtor = realtor
                };
                _emailService.Send(email);
            }
        }

        protected override string GetDetailsUrl(Nominee nominee)
        {
            object param = new { slug = nominee.Slug, id = nominee.Id };
            var uri = new Uri(_baseUrl, Url.Action("Details", "NomineeForening", param));
            return uri.ToString();
        }
    }
}

Presentation.Web/Controllers/NomineeForeningController.cs
using System;
using AutoMapper;
using Core.ApplicationServices;
using Core.DomainModel;
using Core.DomainServices;
using Presentation.Web.Models.Nominee;
using System.Web.Mvc;
using Core.ApplicationServices.Facebook;
using Presentation.Web.Emails;

namespace Presentation.Web.Controllers
{
    public class NomineeForeningController : NomineeControllerBase<ForeningNominee, ForeningDetailsViewModel, ForeningIndexViewModel>
    {
        public NomineeForeningController(
            IMapper mapper,
            IGenericRepository<Nominee> nomineeRepo,
            IContestHelper contestHelper,
            IVoteHelper voteHelper,
            IFacebookAuthHelper fbAuth,
            IFileLocator fileLocator,
            ISettingHelper settingHelper,
            string defaultPicture,
            Uri baseUrl,
            string bannerUrl,
            string twitterShareMessage)
            : base(ContestType.Forening,
                   mapper,
                   nomineeRepo,
                   contestHelper,
                   voteHelper,
                   fbAuth,
                   fileLocator,
                   settingHelper,
                   defaultPicture,
                   baseUrl,
                   bannerUrl,
                   twitterShareMessage) {}

        [HttpGet]
        [Route("~/forening")]
        public override ActionResult Index()
        {
            return base.Index();
        }

        [HttpGet]
        [Route("~/forening/{slug}-{id:int}")]
        public override ActionResult Details(string slug, int id)
        {
            return base.Details(slug, id);
        }

        protected override void SendRecommendEmail(Nominee nominee, RecommendViewModel vm)
        {
            var email = new ForeningRecommendEmail()
            {
                Nominee = (ForeningNominee)nominee,
                NomineeDetailsUrl = GetDetailsUrl(nominee),
                SenderName = vm.SenderName,
                SenderEmail = vm.SenderEmail,
                RecipientName = vm.RecipientName,
                RecipientEmail = vm.RecipientEmail,
                Message = vm.Message,
            };

            email.Send();
        }
    }
}

Presentation.Web/Views/NomineeForening/Index.cshtml
@model Presentation.Web.Models.Nominee.ForeningIndexViewModel
@{
    Layout = "~/Views/Shared/_LayoutForening.cshtml";
    ViewBag.Title = "homePrisen 2018";
    ViewBag.FacebookTrackingEvent = "PageView";
}

<div class="contestActiveElem hidden" data-contest="@Model.IsActive"></div>

<div class="container-fluid header-bg">
    <div class="col-xs-12 header-img" style="background-image: url(@Model.PhotoUrl)">
        <div class="container">
            <div class="row header-container image-header">
                <div class="col-xs-12 col-centered frontpage-title">
                    @Html.Raw(Model.FrontpageTitle)
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-centered frontpage-text">
                    <p>
                        @Html.Raw(Model.FrontpageText)
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-centered header-btn">
                    <a href="@Url.Action("Nominate", "NominateForening")" class="btn btn-header btn-block">Nominér lokalt projekt</a>
                </div>
            </div>
        </div>
        <div class="index-container inActive">
            <div class="container-fluid">
                <div class="row hidden-xs">
                    <form class="form-inline form-inline-desktop-index clearfix search search-desktop">
                        <div class="col-sm-5 col-sm-offset-1 col-lg-3 col-lg-offset-3">
                            <label for="searchInput" class="home-text-font">
                                Se alle de nominerede, og støt dit favorit projekt:
                            </label>
                        </div>
                        <div class="col-sm-3 col-lg-2">
                            <div class="input-group" id="inpu-group">
                                <span class="pull-right input-group-btn">
                                    <button class="btn btn-search searchInput home-text-font" type="submit" value="Test">
                                        <img src="@Url.Content("~/Content/Images/home/home-search-icon.png")" />
                                    </button>
                                </span>
                                <input type="text" class="pull-right form-control phrase bg-search-inactive search-text" placeholder="Søg på navn, postnummer eller by" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2 col-lg-offset-3">
                                <input class="form-control btn btn-search btn-top-15 phrase top-15 home-text-font" type="button" value="Se top 15" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row visible-xs">
    <div class="col-sm-10 col-sm-offset-1">
        <form class="form-horizontal clearfix search search-mobile form-horizontal-mobile-index">
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="searchInput" class="home-text-font">
                        Se alle de nominerede, og støt dit favorit projekt:
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <div class="input-group">
                        <input type="text" class="form-control phrase" placeholder="Søg på navn, postnummer eller by" />
                        <span class="input-group-btn">
                            <button class="btn btn-search searchInput home-text-font" type="submit">
                                <img src="@Url.Content("~/Content/Images/home/home-search-icon.png")" />
                            </button>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <input class="form-control btn btn-search btn-top-15 phrase top-15 home-text-font" type="button" value="Se top 15" />
                </div>
            </div>
        </form>
    </div>
</div>


<div class="inActive">
    <div class="container" id="NomineeList">
        <div class="row hidden no-results">
            <div class="col-xs-10 col-xs-offset-1 text-center">
                <p class="lead">Der blev desværre ikke fundet nogle kandidater</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1 nominees"></div>
        </div>

        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">

                <div class="loader text-center">
                    <img src="/Content/ajaxloader.gif" />
                </div>

                <div class="load-more">
                    <a href="#" class="load-more-container">
                        <div class="show-more text-center">
                            <img class="center-block" src="/Content/Images/Chevron-down.png" />
                            <br />
                            <p>Se flere kandidater</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <p>
                    &nbsp;
                </p>
            </div>
        </div>
    </div>
</div>

<!--Nominee template-->
<div class="hidden nominee-template inActive">
    <div class="col-md-4 nominee-container">
        <div class="row">
            <div class="col-xs-12 nominee-index-profile-pic picture">
                <div class="picture-overlay">
                    <a href="" class="morelink"></a>
                </div>
                <div class="picture-bottom-overlay">
                    <div class="custom-box">
                        <div class="info-panel-container box-margins">
                            <h5 class="text-white rank"></h5>
                            <p class="text-white">Plads</p>
                        </div>
                    </div>
                    <div class="custom-box">
                        <div class="info-panel-container box-margins">
                            <h5 class="text-white voteCount"></h5>
                            <p class="text-white">Stemmer</p>
                        </div>
                    </div>
                    <div class="pull-right">
                        <div class="custom-box pull-left">
                            <div class="info-panel-container">
                                <h4 class="text-white text-share">Del</h4>
                            </div>
                        </div>
                        <div class="custom-box pull-left">
                            <div class="info-panel-container">
                                <div class="fb-share">
                                    <img class="fixed-icon-size" src="~/Content/Images/home/home-fb-icon-invert.png" />
                                </div>
                            </div>
                        </div>
                        <div class="custom-box pull-left">
                            <div class="info-panel-container">
                                <div class="mail-share" data-name="" data-url="@Url.Action("Recommend")">
                                    <img class="fixed-icon-size" src="~/Content/Images/home/home-email-icon-invert.png" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="nominee-info">
            <div class="row">
                <div class="col-xs-12 nominee-header-height">
                    <div class="wrapper">
                        <h4 class="text-index-nominee-header name nominee-header"></h4>
                        <h4 class="text-index-nominee-header city nominee-header"></h4>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 comment-container">
                    <h4>
                        <small class="comment more description nominee-description"></small>
                        <br>
                        <a href="" class="morelink">
                            <small>
                                <b>Læs mere</b>
                            </small>
                        </a>
                        <br>
                        <br>
                    </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-default btn-block voteBtn nominee-btn-overlay">Stem nu</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section head
{
    <meta property="og:image" content="@System.Configuration.ConfigurationManager.AppSettings["BaseUrl"]Content/Images/home/homeprisenfb.png"/>
}

@section scripts
{
    <script type="text/javascript">
        GetNomineesUrl = '@Url.Action("List")';
        GetRanksUrl = '@Url.Action("GetRanks")';
        PlaceVoteUrl = '@Url.Action("PlaceVote")';
        PlaceCommentUrl = '@Url.Action("PlaceComment", "Comment")';
    </script>
    <script type="text/javascript" src="/Scripts/jquery.history.js"></script>
    <script type="text/javascript" src="/Scripts/site/facebook.js"></script>
    <script type="text/javascript" src="/Scripts/site/nominee.js"></script>
    <script type="text/javascript" src="/Scripts/site/home.js"></script>
    <script type="text/javascript" src="/Scripts/site/share.js"></script>
}